services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker: 
    image: devtools:latest
    command: >
      bash -c "
        while true; do
          echo 'Hello from Docker Compose!'
          sleep 5
        done
      "
    depends_on:
      - api
      - redis

  redis: 
    image: redis/redis-stack:latest
    ports: 
      - "6379:6379"
      - "8001:8001"