services:
  api:
    build: .
    image: devtools
    # command: bash -c "python -m devtools.api"

    # somehow --reload below doesn't work, i had to exec into docker and touch api.py to trigger reload
    command: uvicorn devtools.api:app --host 0.0.0.0 --port 8080 --reload
    
    # TODO: didn't work, test some more
    # command: bash -c "python -m debugpy --listen 0.0.0.0:5678 -m uvicorn devtools.api:app --reload --host 0.0.0.0 --port 8080"
    
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      # local ./devtools is mapped into container's /app/devtools for reload upon code change
      - ./devtools:/app/devtools
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - redis

  worker1: 
    image: devtools
    command: bash -c "celery -A devtools.tasks.sample worker -Q xxx --concurrency=1"
    # command: >
    #   bash -c "
    #     while true; do
    #       echo 'Hello from Docker Compose!'
    #       sleep 5
    #     done
    #   "
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - api
      - redis

  worker2: 
    image: devtools
    # command: bash -c "celery -A devtools.tasks.sample worker -Q yyy -E --concurrency=1 --loglevel=DEBUG"
    command: bash -c "celery -A devtools.tasks.sample worker -Q yyy --concurrency=1"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - api
      - redis

  redis: 
    image: redis/redis-stack:latest
    container_name: redis
    ports: 
      - "6379:6379"
      - "8001:8001"

  flower: 
    image: devtools
    command: bash -c "celery -A devtools.app flower --port=7777"
    environment:
      - REDIS_URL=redis://redis:6379
    ports: 
      - "7777:7777"
    depends_on:
      - worker1
      - worker2